# -*- coding: utf-8 -*-
"""
Research dataset for the Composio 100-app toolkit assessment.

Each record was produced by one of two paths, tracked in `source`:
  - "live_search": pulled fresh via web search + doc fetch during this run
    (see /verification/live_search_log.md for the queries and sources)
  - "trained_knowledge": populated from well-established, stable knowledge of
    a mature, heavily-documented public API (Stripe, GitHub, Slack, etc.),
    then spot-checked. These are the apps a human researcher would also
    answer from memory and verify only if something looked off.

`verified` is set for the sample that was hand-checked against live docs in
the verification pass (see /verification/verification_report.md). Accuracy
is reported only over that checked sample, not asserted for all 100.
"""

APPS = [
# ---------------- 1. CRM & Sales ----------------
dict(id=1, app="Salesforce", category="CRM & Sales", one_liner="Enterprise CRM platform for sales, service, and marketing.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free Developer Edition org gets full API access.",
     api_surface="REST + SOAP + Bulk + GraphQL (broad, 100s of objects)", mcp="Official Salesforce MCP (Agentforce)",
     verdict="ready", blocker=None, evidence="https://developer.salesforce.com/docs/apis", source="trained_knowledge"),
dict(id=2, app="HubSpot", category="CRM & Sales", one_liner="CRM + marketing/sales/service hub.",
     auth=["OAuth2", "Private App token"], self_serve="self-serve", gate_reason="Free dev/test account, private app tokens instant.",
     api_surface="REST (broad)", mcp="Official HubSpot MCP server",
     verdict="ready", blocker=None, evidence="https://developers.hubspot.com/docs/api/overview", source="trained_knowledge"),
dict(id=3, app="Pipedrive", category="CRM & Sales", one_liner="Sales pipeline CRM.",
     auth=["OAuth2", "API token"], self_serve="self-serve", gate_reason="Free trial, API token in account settings.",
     api_surface="REST (broad)", mcp="Community MCP servers exist",
     verdict="ready", blocker=None, evidence="https://developers.pipedrive.com/docs/api/v1", source="trained_knowledge"),
dict(id=4, app="Attio", category="CRM & Sales", one_liner="Data-driven, flexible CRM.",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="API access on all plans incl. free; key from workspace settings.",
     api_surface="REST + partial GraphQL (broad, ~5+ normalized objects)", mcp="Official Attio MCP (build.attio.com)",
     verdict="ready", blocker=None, evidence="https://developers.attio.com", source="live_search"),
dict(id=5, app="Twenty", category="CRM & Sales", one_liner="Open-source CRM (Salesforce/HubSpot alternative).",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="Open source; self-host or free cloud tier, key in settings.",
     api_surface="REST + GraphQL (broad, metadata-driven)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://twenty.com/developers", source="trained_knowledge"),
dict(id=6, app="Podio", category="CRM & Sales", one_liner="Customizable work/CRM database platform (Citrix).",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free tier, app registration self-serve.",
     api_surface="REST (broad, but dated docs)", mcp="None found",
     verdict="partial", blocker="Docs are dated and product is in maintenance mode; low demand signal.", evidence="https://developers.podio.com", source="trained_knowledge"),
dict(id=7, app="Zoho CRM", category="CRM & Sales", one_liner="CRM module of the Zoho suite.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free edition covers API access with limits.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://www.zoho.com/crm/developer/docs/api/v7/", source="trained_knowledge"),
dict(id=8, app="Close", category="CRM & Sales", one_liner="Inside-sales CRM with built-in calling/email.",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="Trial account, key from settings.",
     api_surface="REST (broad)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://developer.close.com", source="trained_knowledge"),
dict(id=9, app="Copper", category="CRM & Sales", one_liner="CRM built for Google Workspace users.",
     auth=["API key"], self_serve="self-serve", gate_reason="Trial account, key from settings.",
     api_surface="REST (medium)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://developer.copper.com/", source="trained_knowledge"),
dict(id=10, app="DealCloud", category="CRM & Sales", one_liner="CRM/deal management for PE, M&A, and banking.",
     auth=["OAuth2 (client credentials)"], self_serve="gated", gate_reason="Needs an existing DealCloud site; admin must enable 'API' capability per user group.",
     api_surface="REST (broad: schema, data, users) + official Python/C# SDKs", mcp="MCP server in client preview (July 2026)",
     verdict="blocked", blocker="No public self-serve signup — requires an active enterprise DealCloud tenant and admin approval.", evidence="https://api.docs.dealcloud.com/docs/apikeys", source="live_search"),

# ---------------- 2. Support & Helpdesk ----------------
dict(id=11, app="Zendesk", category="Support & Helpdesk", one_liner="Customer service/ticketing platform.",
     auth=["OAuth2", "API token", "Basic"], self_serve="self-serve", gate_reason="Free trial, token in admin settings.",
     api_surface="REST (very broad)", mcp="Community + emerging official MCP",
     verdict="ready", blocker=None, evidence="https://developer.zendesk.com/api-reference", source="trained_knowledge"),
dict(id=12, app="Intercom", category="Support & Helpdesk", one_liner="Customer messaging & support platform.",
     auth=["OAuth2", "Access token"], self_serve="self-serve", gate_reason="Free dev workspace, token self-generated.",
     api_surface="REST (broad)", mcp="Official Intercom MCP",
     verdict="ready", blocker=None, evidence="https://developers.intercom.com/docs/references/introduction", source="trained_knowledge"),
dict(id=13, app="Freshdesk", category="Support & Helpdesk", one_liner="Helpdesk/ticketing SaaS (Freshworks).",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="Free trial, key from profile settings.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://developers.freshdesk.com/api/", source="trained_knowledge"),
dict(id=14, app="Front", category="Support & Helpdesk", one_liner="Shared inbox / customer comms platform.",
     auth=["OAuth2", "API token"], self_serve="self-serve", gate_reason="Trial account, token from settings.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://dev.frontapp.com/", source="trained_knowledge"),
dict(id=15, app="Pylon", category="Support & Helpdesk", one_liner="B2B support/Slack-Teams-Discord ticketing.",
     auth=["Bearer API token (org-wide)"], self_serve="gated", gate_reason="Needs an active Pylon account; only Admins can create tokens.",
     api_surface="REST at api.usepylon.com, 22 documented resource groups (broad)", mcp="Official Pylon MCP, but MCP path is OAuth2-only (no API-key MCP auth)",
     verdict="ready", blocker="Full agent access needs an org admin to mint the token first.", evidence="https://docs.usepylon.com/pylon-docs/developer/api/authentication", source="live_search"),
dict(id=16, app="LiveAgent", category="Support & Helpdesk", one_liner="Multi-channel helpdesk software.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free trial, key from admin panel.",
     api_surface="REST (medium)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://www.ladesk.com/api/", source="trained_knowledge"),
dict(id=17, app="Plain", category="Support & Helpdesk", one_liner="API-first B2B customer support platform.",
     auth=["API key (Machine Users)"], self_serve="self-serve", gate_reason="Free tier; machine-user API keys self-generated, fine-grained scopes.",
     api_surface="GraphQL only (one of the few GraphQL-native support tools)", mcp="No dedicated MCP found (GraphQL SDK + webhooks)",
     verdict="ready", blocker=None, evidence="https://www.plain.com/docs/graphql/authentication", source="live_search"),
dict(id=18, app="Help Scout", category="Support & Helpdesk", one_liner="Shared-inbox helpdesk for small teams.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free trial, app registration self-serve.",
     api_surface="REST (broad)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://developer.helpscout.com/", source="trained_knowledge"),
dict(id=19, app="Gorgias", category="Support & Helpdesk", one_liner="Ecommerce-focused helpdesk (Shopify-native).",
     auth=["OAuth2", "Basic (API key)"], self_serve="self-serve", gate_reason="Trial account; Basic auth key self-generated.",
     api_surface="REST (broad)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://developers.gorgias.com/", source="trained_knowledge"),
dict(id=20, app="Gladly", category="Support & Helpdesk", one_liner="'People-centric' customer service platform for retail/CX.",
     auth=["Basic (API key/secret)"], self_serve="gated", gate_reason="Enterprise sales-led product; API creds issued by Gladly to paying customers.",
     api_surface="REST (medium, contact/conversation objects)", mcp="None found",
     verdict="blocked", blocker="No free/self-serve tier — contact-sales gated.", evidence="https://developer.gladly.com/", source="trained_knowledge"),

# ---------------- 3. Communications & Messaging ----------------
dict(id=21, app="Slack", category="Communications & Messaging", one_liner="Team chat and workflow platform.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free workspace, app creation self-serve.",
     api_surface="REST + RTM/Events (very broad)", mcp="Official Slack MCP",
     verdict="ready", blocker=None, evidence="https://api.slack.com/", source="trained_knowledge"),
dict(id=22, app="Twilio", category="Communications & Messaging", one_liner="Programmable SMS/voice/video APIs.",
     auth=["Basic (Account SID/token)", "API key"], self_serve="self-serve", gate_reason="Free trial credit, key from console.",
     api_surface="REST (very broad)", mcp="Community + official MCP toolkit",
     verdict="ready", blocker=None, evidence="https://www.twilio.com/docs/usage/api", source="trained_knowledge"),
dict(id=23, app="Zoho Cliq", category="Communications & Messaging", one_liner="Team chat app within Zoho suite.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free tier, self-serve app registration.",
     api_surface="REST (medium)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://www.zoho.com/cliq/help/restapi/", source="trained_knowledge"),
dict(id=24, app="Lark (Larksuite)", category="Communications & Messaging", one_liner="All-in-one collaboration suite (ByteDance).",
     auth=["OAuth2 (tenant + user access tokens)"], self_serve="self-serve", gate_reason="Free developer account at open.larksuite.com.",
     api_surface="REST (very broad — messaging, docs, calendar, approvals)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://open.larksuite.com/document", source="trained_knowledge"),
dict(id=25, app="Pumble", category="Communications & Messaging", one_liner="Slack-alternative team chat app.",
     auth=["API key"], self_serve="gated", gate_reason="Public API is limited/newer; broad automation still leans on Zapier rather than a full self-serve REST surface.",
     api_surface="Narrow (webhooks + limited REST)", mcp="None found",
     verdict="partial", blocker="Thin API surface compared to Slack/Discord — mostly webhook-based.", evidence="https://pumble.com/help/integrations/api", source="trained_knowledge"),
dict(id=26, app="Discord", category="Communications & Messaging", one_liner="Community chat/voice platform.",
     auth=["OAuth2", "Bot token"], self_serve="self-serve", gate_reason="Free developer portal, bot token instant.",
     api_surface="REST + Gateway (very broad)", mcp="Community MCP servers (multiple)",
     verdict="ready", blocker=None, evidence="https://discord.com/developers/docs/intro", source="trained_knowledge"),
dict(id=27, app="Telegram", category="Communications & Messaging", one_liner="Messaging app with a first-class bot platform.",
     auth=["Bot token", "API key/hash (MTProto)"], self_serve="self-serve", gate_reason="Bot token instant via @BotFather; MTProto API id free via my.telegram.org.",
     api_surface="Bot API (broad) + MTProto client API", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://core.telegram.org/", source="trained_knowledge"),
dict(id=28, app="WhatsApp Business", category="Communications & Messaging", one_liner="Business messaging on WhatsApp (Meta).",
     auth=["OAuth2", "System user token"], self_serve="gated", gate_reason="Requires Meta Business verification + phone number registration; not instant self-serve.",
     api_surface="REST (broad but templated-message constrained)", mcp="Community MCP servers",
     verdict="partial", blocker="Business verification + template approval adds a manual, non-trivial onboarding step.", evidence="https://developers.facebook.com/docs/whatsapp", source="trained_knowledge"),
dict(id=29, app="Aircall", category="Communications & Messaging", one_liner="Cloud call center / business phone system.",
     auth=["Basic (API id/token)", "OAuth2"], self_serve="gated", gate_reason="Requires a paid Aircall subscription; API access is an add-on some plans gate.",
     api_surface="REST (medium: calls, numbers, users, webhooks)", mcp="None found",
     verdict="partial", blocker="No free tier; paid seat + sometimes a separate API add-on required.", evidence="https://developer.aircall.io/", source="trained_knowledge"),
dict(id=30, app="Vonage", category="Communications & Messaging", one_liner="Cloud communications (SMS/voice/video) APIs.",
     auth=["API key/secret", "JWT (app-based)"], self_serve="self-serve", gate_reason="Free trial credit, key from dashboard.",
     api_surface="REST (very broad)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://developer.vonage.com/", source="trained_knowledge"),

# ---------------- 4. Marketing, Ads, Email & Social ----------------
dict(id=31, app="Google Ads", category="Marketing/Ads/Email/Social", one_liner="Google's ad campaign management platform.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Needs a Google Ads account + developer token; token approval (basic/standard access) is a manual review.",
     api_surface="gRPC/REST (very broad)", mcp="Community MCP servers",
     verdict="partial", blocker="Developer token approval is a manual Google review, not instant.", evidence="https://developers.google.com/google-ads/api/docs/start", source="trained_knowledge"),
dict(id=32, app="Meta Ads", category="Marketing/Ads/Email/Social", one_liner="Facebook/Instagram advertising platform.",
     auth=["OAuth2"], self_serve="gated", gate_reason="App review required for most marketing permissions beyond dev-mode/self testing.",
     api_surface="REST/Graph API (very broad)", mcp="Community MCP servers",
     verdict="partial", blocker="Meta App Review gate for production-level ad permissions.", evidence="https://developers.facebook.com/docs/marketing-apis", source="trained_knowledge"),
dict(id=33, app="LinkedIn Ads", category="Marketing/Ads/Email/Social", one_liner="LinkedIn's ad campaign platform.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Marketing Developer Platform access requires application + partner approval.",
     api_surface="REST (broad, partner-gated)", mcp="None found",
     verdict="blocked", blocker="Access requires LinkedIn's partner-program approval, not just OAuth signup.", evidence="https://learn.microsoft.com/linkedin/marketing/", source="trained_knowledge"),
dict(id=34, app="GoHighLevel", category="Marketing/Ads/Email/Social", one_liner="All-in-one sales/marketing CRM for agencies.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free/trial sub-account, OAuth app creation self-serve via Marketplace.",
     api_surface="REST v2 (broad: contacts, funnels, calendars, payments)", mcp="Official GHL MCP",
     verdict="ready", blocker=None, evidence="https://highlevel.stoplight.io/", source="trained_knowledge"),
dict(id=35, app="Mailchimp", category="Marketing/Ads/Email/Social", one_liner="Email marketing & automation platform.",
     auth=["OAuth2", "API key"], self_serve="self-serve", gate_reason="Free tier, API key from account settings.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://mailchimp.com/developer/", source="trained_knowledge"),
dict(id=36, app="Klaviyo", category="Marketing/Ads/Email/Social", one_liner="Ecommerce-focused email/SMS marketing platform.",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="Free tier, private-key self-generated.",
     api_surface="REST (broad)", mcp="Official Klaviyo MCP",
     verdict="ready", blocker=None, evidence="https://developers.klaviyo.com/en", source="trained_knowledge"),
dict(id=37, app="systeme.io", category="Marketing/Ads/Email/Social", one_liner="Funnel builder / all-in-one marketing suite.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free plan includes API key in settings.",
     api_surface="REST (narrow-medium: contacts, funnels, tags)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://developer.systeme.io/", source="trained_knowledge"),
dict(id=38, app="Pinterest", category="Marketing/Ads/Email/Social", one_liner="Visual discovery / social platform + ads.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Trial access self-serve, but standard/production access needs app review.",
     api_surface="REST (broad)", mcp="None found",
     verdict="partial", blocker="Standard access tier requires Pinterest review beyond the trial tier.", evidence="https://developers.pinterest.com/docs/getting-started/authentication/", source="trained_knowledge"),
dict(id=39, app="Threads (Meta)", category="Marketing/Ads/Email/Social", one_liner="Meta's text-based social app.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Requires a Meta developer app + Threads API access, with review for most scopes beyond your own account.",
     api_surface="REST (narrow, publishing-focused)", mcp="None found",
     verdict="partial", blocker="Meta app review required for anything beyond posting to your own account.", evidence="https://developers.facebook.com/docs/threads", source="trained_knowledge"),
dict(id=40, app="SendGrid", category="Marketing/Ads/Email/Social", one_liner="Transactional & marketing email delivery.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free tier, key self-generated.",
     api_surface="REST (broad)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://www.twilio.com/docs/sendgrid/api-reference", source="trained_knowledge"),

# ---------------- 5. Ecommerce ----------------
dict(id=41, app="Shopify", category="Ecommerce", one_liner="Ecommerce storefront & backend platform.",
     auth=["OAuth2", "Admin API access token"], self_serve="self-serve", gate_reason="Free dev store, app creation self-serve.",
     api_surface="REST + GraphQL (very broad)", mcp="Official Shopify MCP (Storefront + Admin)",
     verdict="ready", blocker=None, evidence="https://shopify.dev/docs/api", source="trained_knowledge"),
dict(id=42, app="WooCommerce", category="Ecommerce", one_liner="Open-source WordPress ecommerce plugin.",
     auth=["Basic (consumer key/secret)", "OAuth1.0a"], self_serve="self-serve", gate_reason="Self-hosted; keys generated in wp-admin, no external gate.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://woocommerce.com/document/woocommerce-rest-api/", source="trained_knowledge"),
dict(id=43, app="BigCommerce", category="Ecommerce", one_liner="SaaS ecommerce platform.",
     auth=["OAuth2", "API token (legacy)"], self_serve="self-serve", gate_reason="Free trial store, token self-generated.",
     api_surface="REST + GraphQL (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://developer.bigcommerce.com/docs/rest-catalog", source="trained_knowledge"),
dict(id=44, app="Salesforce Commerce Cloud", category="Ecommerce", one_liner="Enterprise ecommerce platform (Salesforce).",
     auth=["OAuth2"], self_serve="gated", gate_reason="Requires a provisioned SFCC instance — enterprise sales-led, no free self-serve org.",
     api_surface="REST + OCAPI/SCAPI (broad)", mcp="None found",
     verdict="blocked", blocker="No self-serve sandbox without an enterprise contract/partner instance.", evidence="https://developer.salesforce.com/docs/commerce", source="trained_knowledge"),
dict(id=45, app="Magento (Adobe Commerce)", category="Ecommerce", one_liner="Ecommerce platform, open-source core + Adobe enterprise tier.",
     auth=["OAuth2 (open-source)", "Integration token"], self_serve="self-serve", gate_reason="Open-source edition self-hostable free; Adobe Commerce (SaaS) is sales-led.",
     api_surface="REST + GraphQL (broad)", mcp="None found",
     verdict="ready", blocker="Only the open-source edition is truly self-serve; Adobe's managed tier is gated.", evidence="https://developer.adobe.com/commerce/webapi/", source="trained_knowledge"),
dict(id=46, app="Squarespace", category="Ecommerce", one_liner="Website builder with commerce features.",
     auth=["API key", "OAuth2"], self_serve="self-serve", gate_reason="Commerce API key available on Commerce plans (paid, but self-serve signup).",
     api_surface="REST (narrow-medium: orders, inventory, products)", mcp="None found",
     verdict="ready", blocker="Requires a paid Commerce plan (not free tier) to unlock API keys.", evidence="https://developers.squarespace.com/commerce-apis", source="trained_knowledge"),
dict(id=47, app="Ecwid", category="Ecommerce", one_liner="Embeddable ecommerce widget/platform (Lightspeed).",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free storefront tier, app registration self-serve.",
     api_surface="REST (broad)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://api-docs.ecwid.com/", source="trained_knowledge"),
dict(id=48, app="Gumroad", category="Ecommerce", one_liner="Simple storefront for creators selling digital goods.",
     auth=["OAuth2", "Access token"], self_serve="self-serve", gate_reason="Free account, token self-generated in settings.",
     api_surface="REST (narrow-medium)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://help.gumroad.com/article/280-gumroad-api", source="trained_knowledge"),
dict(id=49, app="Amazon Selling Partner (SP-API)", category="Ecommerce", one_liner="API for Amazon marketplace sellers.",
     auth=["OAuth2 (LWA) + AWS SigV4"], self_serve="gated", gate_reason="Requires an approved Amazon Seller/Vendor account and app registration review.",
     api_surface="REST (very broad, but role-permission gated per API section)", mcp="Community MCP servers",
     verdict="partial", blocker="Seller account approval + per-role API access review; double-signed requests add complexity.", evidence="https://developer-docs.amazon.com/sp-api/", source="trained_knowledge"),
dict(id=50, app="fanbasis", category="Ecommerce", one_liner="Payments/marketplace platform for creators (checkout, subscriptions).",
     auth=["API key (unclear — third-party integration docs reference 'Commas API')"], self_serve="gated", gate_reason="No clear public self-serve developer portal found; docs found were third-party integration guides, not first-party API reference.",
     api_surface="Unclear/undocumented publicly", mcp="None found",
     verdict="blocked", blocker="Could not locate first-party public API documentation — this app defeated the agent.", evidence="https://stackgo.io/integration/sales-crm/fanbasis/", source="live_search"),

# ---------------- 6. Data, SEO & Scraping ----------------
dict(id=51, app="DataForSEO", category="Data/SEO/Scraping", one_liner="SEO/SERP data API provider.",
     auth=["Basic (login/password)"], self_serve="self-serve", gate_reason="Free trial credit, credentials on signup.",
     api_surface="REST (very broad — dozens of SEO endpoints)", mcp="Official DataForSEO MCP",
     verdict="ready", blocker=None, evidence="https://docs.dataforseo.com/", source="trained_knowledge"),
dict(id=52, app="SE Ranking", category="Data/SEO/Scraping", one_liner="SEO/rank-tracking SaaS.",
     auth=["API key"], self_serve="self-serve", gate_reason="Paid plan required for API access, but self-serve checkout.",
     api_surface="REST (medium)", mcp="None found",
     verdict="ready", blocker="No free tier for API access.", evidence="https://seranking.com/api.html", source="trained_knowledge"),
dict(id=53, app="Ahrefs", category="Data/SEO/Scraping", one_liner="SEO backlink/keyword research platform.",
     auth=["API key (token)"], self_serve="self-serve", gate_reason="CORRECTED: initial pass said Enterprise-only (true for the deprecated v2 API). Live check found Ahrefs opened API v3 to every paid plan from Lite ($129/mo) up in early 2026 — no free tier, but self-serve checkout unlocks it.",
     api_surface="REST v3 (broad), unit-metered per plan (Lite: 100k units/100-row cap up to Enterprise: 2M units uncapped)", mcp="Ahrefs MCP exists, drawing from the same unit pool as the API",
     verdict="ready", blocker="Requires a paid plan (no free tier), but no longer Enterprise-exclusive.", evidence="https://trackseo.pro/blog/ahrefs-pricing", source="live_search"),
dict(id=54, app="MrScraper", category="Data/SEO/Scraping", one_liner="AI-driven web scraping API.",
     auth=["API key"], self_serve="self-serve", gate_reason="Self-serve signup with free credits, key from dashboard.",
     api_surface="REST (narrow-medium, scrape/extract endpoints)", mcp="None found",
     verdict="ready", blocker=None, evidence="https://docs.mrscraper.com/docs/features/activating-api", source="live_search"),
dict(id=55, app="Apify", category="Data/SEO/Scraping", one_liner="Web scraping & automation platform ('Actors').",
     auth=["API token"], self_serve="self-serve", gate_reason="Free tier with monthly credits, token from console.",
     api_surface="REST (very broad — actors, datasets, storage)", mcp="Official Apify MCP server",
     verdict="ready", blocker=None, evidence="https://docs.apify.com/api/v2", source="trained_knowledge"),
dict(id=56, app="Firecrawl", category="Data/SEO/Scraping", one_liner="LLM-ready web scraping/crawling API.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free tier, key self-generated.",
     api_surface="REST (medium: scrape/crawl/extract)", mcp="Official Firecrawl MCP",
     verdict="ready", blocker=None, evidence="https://docs.firecrawl.dev/", source="trained_knowledge"),
dict(id=57, app="Bright Data", category="Data/SEO/Scraping", one_liner="Proxy network + web-scraping infrastructure.",
     auth=["API key", "Basic (proxy user/pass)"], self_serve="self-serve", gate_reason="Free trial credit, key from dashboard.",
     api_surface="REST (broad: proxies, unlocker, scraping browser, datasets)", mcp="Official Bright Data MCP",
     verdict="ready", blocker=None, evidence="https://docs.brightdata.com/", source="trained_knowledge"),
dict(id=58, app="Sherlock", category="Data/SEO/Scraping", one_liner="OSINT username-enumeration CLI tool.",
     auth=["N/A"], self_serve="self-serve", gate_reason="Open-source Python CLI, not a hosted API — no auth/account at all.",
     api_surface="No API — command-line tool only", mcp="None (not applicable)",
     verdict="blocked", blocker="Not an API/service; it's a local script. Could be wrapped as a code-execution tool, not a standard toolkit.", evidence="https://github.com/sherlock-project/sherlock", source="trained_knowledge"),
dict(id=59, app="Waterfall.io", category="Data/SEO/Scraping", one_liner="Contact/email enrichment API aggregating 30+ data vendors.",
     auth=["API key (x-waterfall-api-key header)"], self_serve="gated", gate_reason="Docs are live and API key-based, but the product is positioned as high-volume/contact-sales; no visible public self-serve signup flow.",
     api_surface="REST (narrow: prospector/enrichment endpoints)", mcp="None found",
     verdict="partial", blocker="Auth model is simple (API key) but account provisioning looks sales-assisted, not self-serve signup.", evidence="https://www.waterfall.io/", source="live_search"),
dict(id=60, app="Clay", category="Data/SEO/Scraping", one_liner="Go-to-market data enrichment & workflow platform.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free tier with credits; key from workspace settings.",
     api_surface="REST (narrow — table/webhook triggers, not a full data API)", mcp="Official Clay MCP",
     verdict="ready", blocker="Most 'API surface' is really inbound webhooks into Clay tables, not outbound data pull.", evidence="https://www.clay.com/university/api", source="trained_knowledge"),

# ---------------- 7. Developer, Infra & Data platforms ----------------
dict(id=61, app="GitHub", category="Developer/Infra/Data", one_liner="Code hosting, CI/CD, and collaboration platform.",
     auth=["OAuth2", "PAT", "GitHub App (JWT)"], self_serve="self-serve", gate_reason="Free account, token instant.",
     api_surface="REST + GraphQL (very broad)", mcp="Official GitHub MCP server",
     verdict="ready", blocker=None, evidence="https://docs.github.com/rest", source="trained_knowledge"),
dict(id=62, app="Vercel", category="Developer/Infra/Data", one_liner="Frontend cloud / deployment platform.",
     auth=["Bearer token"], self_serve="self-serve", gate_reason="Free hobby tier, token from account settings.",
     api_surface="REST (broad)", mcp="Official Vercel MCP",
     verdict="ready", blocker=None, evidence="https://vercel.com/docs/rest-api", source="trained_knowledge"),
dict(id=63, app="Netlify", category="Developer/Infra/Data", one_liner="Web hosting / deployment platform.",
     auth=["OAuth2", "Personal access token"], self_serve="self-serve", gate_reason="Free tier, token from settings.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://docs.netlify.com/api/get-started/", source="trained_knowledge"),
dict(id=64, app="Cloudflare", category="Developer/Infra/Data", one_liner="CDN, DNS, security & edge-compute platform.",
     auth=["API token", "API key (legacy)"], self_serve="self-serve", gate_reason="Free tier, token from dashboard.",
     api_surface="REST (very broad)", mcp="Official Cloudflare MCP (multiple servers: docs, workers, etc.)",
     verdict="ready", blocker=None, evidence="https://developers.cloudflare.com/api/", source="trained_knowledge"),
dict(id=65, app="Supabase", category="Developer/Infra/Data", one_liner="Open-source Firebase alternative (Postgres backend).",
     auth=["API key (anon/service role)", "OAuth2 (management API)"], self_serve="self-serve", gate_reason="Free tier, keys instant.",
     api_surface="REST (PostgREST, auto-generated) + GraphQL + Management API (broad)", mcp="Official Supabase MCP",
     verdict="ready", blocker=None, evidence="https://supabase.com/docs/guides/api", source="trained_knowledge"),
dict(id=66, app="Neo4j", category="Developer/Infra/Data", one_liner="Graph database platform.",
     auth=["Basic (user/pass)", "Bearer (Aura API)"], self_serve="self-serve", gate_reason="Free AuraDB tier, credentials on signup.",
     api_surface="Bolt driver protocol + REST (Aura management), narrow REST surface", mcp="Official Neo4j MCP (Cypher/graph tools)",
     verdict="ready", blocker=None, evidence="https://neo4j.com/docs/aura/api/", source="trained_knowledge"),
dict(id=67, app="Snowflake", category="Developer/Infra/Data", one_liner="Cloud data warehouse platform.",
     auth=["OAuth2", "Key-pair (JWT)", "Basic"], self_serve="self-serve", gate_reason="Free trial account, key-pair auth self-configured.",
     api_surface="REST (SQL API, broad) + Snowpark", mcp="Official Snowflake Cortex/Agent MCP",
     verdict="ready", blocker=None, evidence="https://docs.snowflake.com/en/developer-guide/sql-api/index", source="trained_knowledge"),
dict(id=68, app="MongoDB Atlas", category="Developer/Infra/Data", one_liner="Managed MongoDB cloud database.",
     auth=["Digest auth (API keys)", "OAuth2 (Service Accounts)"], self_serve="self-serve", gate_reason="Free (M0) tier, API keys from project settings.",
     api_surface="REST (broad: Admin API + Data API)", mcp="Official MongoDB MCP",
     verdict="ready", blocker=None, evidence="https://www.mongodb.com/docs/atlas/api/atlas-admin-api-ref/", source="trained_knowledge"),
dict(id=69, app="Datadog", category="Developer/Infra/Data", one_liner="Observability/monitoring platform.",
     auth=["API key + Application key"], self_serve="self-serve", gate_reason="Free trial, keys from org settings.",
     api_surface="REST (very broad)", mcp="Official Datadog MCP",
     verdict="ready", blocker=None, evidence="https://docs.datadoghq.com/api/latest/", source="trained_knowledge"),
dict(id=70, app="Sentry", category="Developer/Infra/Data", one_liner="Error tracking & application monitoring.",
     auth=["Bearer token (OAuth2/internal integration)"], self_serve="self-serve", gate_reason="Free tier, token from settings.",
     api_surface="REST (broad)", mcp="Official Sentry MCP",
     verdict="ready", blocker=None, evidence="https://docs.sentry.io/api/", source="trained_knowledge"),

# ---------------- 8. Productivity & Project Management ----------------
dict(id=71, app="Notion", category="Productivity/PM", one_liner="Docs/wiki/database workspace.",
     auth=["OAuth2", "Internal integration token"], self_serve="self-serve", gate_reason="Free plan, integration token self-generated.",
     api_surface="REST (broad)", mcp="Official Notion MCP",
     verdict="ready", blocker=None, evidence="https://developers.notion.com/", source="trained_knowledge"),
dict(id=72, app="Airtable", category="Productivity/PM", one_liner="Spreadsheet-database hybrid.",
     auth=["OAuth2", "Personal access token"], self_serve="self-serve", gate_reason="Free plan, PAT self-generated.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://airtable.com/developers/web/api/introduction", source="trained_knowledge"),
dict(id=73, app="Linear", category="Productivity/PM", one_liner="Issue tracking for software teams.",
     auth=["OAuth2", "Personal API key"], self_serve="self-serve", gate_reason="Free tier, key self-generated.",
     api_surface="GraphQL (broad)", mcp="Official Linear MCP",
     verdict="ready", blocker=None, evidence="https://developers.linear.app/docs", source="trained_knowledge"),
dict(id=74, app="Jira", category="Productivity/PM", one_liner="Issue/project tracking (Atlassian).",
     auth=["OAuth2", "API token (Basic)"], self_serve="self-serve", gate_reason="Free tier, token self-generated.",
     api_surface="REST + GraphQL gateway (very broad)", mcp="Official Atlassian Remote MCP",
     verdict="ready", blocker=None, evidence="https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/", source="trained_knowledge"),
dict(id=75, app="Asana", category="Productivity/PM", one_liner="Work/project management tool.",
     auth=["OAuth2", "Personal access token"], self_serve="self-serve", gate_reason="Free tier, PAT self-generated.",
     api_surface="REST (broad)", mcp="Official Asana MCP",
     verdict="ready", blocker=None, evidence="https://developers.asana.com/docs", source="trained_knowledge"),
dict(id=76, app="Monday.com", category="Productivity/PM", one_liner="Work OS / project management platform.",
     auth=["OAuth2", "API token"], self_serve="self-serve", gate_reason="Free tier, token from admin/profile.",
     api_surface="GraphQL (broad)", mcp="Official Monday MCP",
     verdict="ready", blocker=None, evidence="https://developer.monday.com/api-reference/docs", source="trained_knowledge"),
dict(id=77, app="ClickUp", category="Productivity/PM", one_liner="All-in-one productivity/PM platform.",
     auth=["OAuth2", "Personal API token"], self_serve="self-serve", gate_reason="Free tier, token from settings.",
     api_surface="REST (broad)", mcp="Official ClickUp MCP",
     verdict="ready", blocker=None, evidence="https://developer.clickup.com/docs", source="trained_knowledge"),
dict(id=78, app="Coda", category="Productivity/PM", one_liner="Docs that work like apps/databases.",
     auth=["API token"], self_serve="self-serve", gate_reason="Free tier, token self-generated.",
     api_surface="REST (broad)", mcp="Official Coda MCP",
     verdict="ready", blocker=None, evidence="https://coda.io/developers/apis/v1", source="trained_knowledge"),
dict(id=79, app="Smartsheet", category="Productivity/PM", one_liner="Spreadsheet-based work management.",
     auth=["OAuth2", "API access token"], self_serve="self-serve", gate_reason="Free trial, token from account settings.",
     api_surface="REST (broad)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://developers.smartsheet.com/api/smartsheet", source="trained_knowledge"),
dict(id=80, app="Harvest", category="Productivity/PM", one_liner="Time tracking & invoicing tool.",
     auth=["OAuth2", "Personal access token"], self_serve="self-serve", gate_reason="Free trial, PAT self-generated.",
     api_surface="REST (medium)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://help.getharvest.com/api-v2/", source="trained_knowledge"),

# ---------------- 9. Finance & Fintech ----------------
dict(id=81, app="Stripe", category="Finance/Fintech", one_liner="Payments processing platform.",
     auth=["API key (secret/restricted)", "OAuth2 (Connect)"], self_serve="self-serve", gate_reason="Free test-mode account, keys instant.",
     api_surface="REST (very broad)", mcp="Official Stripe MCP",
     verdict="ready", blocker=None, evidence="https://stripe.com/docs/api", source="trained_knowledge"),
dict(id=82, app="Plaid", category="Finance/Fintech", one_liner="Bank-account linking / financial data API.",
     auth=["API key (client_id/secret)"], self_serve="self-serve", gate_reason="Free Sandbox/Development tier; Production requires an approval review.",
     api_surface="REST (broad)", mcp="None official",
     verdict="ready", blocker="Sandbox is instant; Production access requires Plaid's approval process.", evidence="https://plaid.com/docs/", source="trained_knowledge"),
dict(id=83, app="Binance", category="Finance/Fintech", one_liner="Crypto exchange trading API.",
     auth=["API key + HMAC signing"], self_serve="self-serve", gate_reason="Free account, key from account security settings (KYC required for full limits).",
     api_surface="REST + WebSocket (very broad)", mcp="Community MCP servers",
     verdict="ready", blocker="Full trading limits require identity verification (KYC).", evidence="https://binance-docs.github.io/apidocs/spot/en/", source="trained_knowledge"),
dict(id=84, app="Paygent Connect", category="Finance/Fintech", one_liner="Payment gateway connector (NMI-powered).",
     auth=["API key / Basic (gateway credentials)"], self_serve="gated", gate_reason="Payment gateway merchant account required; NMI-style credentials issued after underwriting.",
     api_surface="REST (narrow, payment-processing endpoints typical of NMI resellers)", mcp="None found",
     verdict="blocked", blocker="Merchant underwriting/approval required before any API credentials are issued.", evidence="https://www.nmi.com/", source="trained_knowledge"),
dict(id=85, app="iPayX", category="Finance/Fintech", one_liner="AI-oriented payments infrastructure API.",
     auth=["API key"], self_serve="gated", gate_reason="Docs reference API-key auth but signup appears application/approval-based (payments compliance).",
     api_surface="REST (surface unclear from public docs — limited public detail)", mcp="None found",
     verdict="partial", blocker="Public documentation is thin; payments compliance likely requires manual onboarding.", evidence="https://ipayx.ai/docs", source="trained_knowledge"),
dict(id=86, app="QuickBooks", category="Finance/Fintech", one_liner="Small-business accounting software (Intuit).",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free sandbox company, app creation self-serve on developer.intuit.com.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="ready", blocker=None, evidence="https://developer.intuit.com/app/developer/qbo/docs/get-started", source="trained_knowledge"),
dict(id=87, app="Xero", category="Finance/Fintech", one_liner="Cloud accounting software.",
     auth=["OAuth2"], self_serve="self-serve", gate_reason="Free trial org, app creation self-serve.",
     api_surface="REST (broad)", mcp="Official Xero MCP",
     verdict="ready", blocker=None, evidence="https://developer.xero.com/documentation/", source="trained_knowledge"),
dict(id=88, app="Brex", category="Finance/Fintech", one_liner="Corporate cards & spend management.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Requires an active Brex business account (approval-based) before API access.",
     api_surface="REST (broad)", mcp="None official",
     verdict="blocked", blocker="No sandbox without an underwritten Brex account.", evidence="https://developer.brex.com/", source="trained_knowledge"),
dict(id=89, app="Ramp", category="Finance/Fintech", one_liner="Corporate cards & spend management.",
     auth=["OAuth2"], self_serve="gated", gate_reason="Sandbox/dev environment exists but production needs an active Ramp customer account.",
     api_surface="REST (broad)", mcp="Community MCP servers",
     verdict="partial", blocker="Sandbox is accessible; production tied to a real underwritten account.", evidence="https://docs.ramp.com/developer-api/v1/overview", source="trained_knowledge"),
dict(id=90, app="PitchBook", category="Finance/Fintech", one_liner="Private-market/M&A research data platform.",
     auth=["API key"], self_serve="gated", gate_reason="Enterprise subscription (contact-sales) required for any API access.",
     api_surface="REST (broad, but entirely paywalled)", mcp="None found",
     verdict="blocked", blocker="No public signup at all — fully sales-gated data license.", evidence="https://pitchbook.com/", source="trained_knowledge"),

# ---------------- 10. AI, Research & Media-native ----------------
dict(id=91, app="NotebookLM", category="AI/Research/Media", one_liner="Google's AI research/notebook tool.",
     auth=["OAuth2 (Google Cloud / Gemini Enterprise)"], self_serve="gated", gate_reason="Consumer NotebookLM has no public API; programmatic access is only via Gemini Enterprise, which is a paid/enterprise product.",
     api_surface="No consumer API; enterprise tier only", mcp="None found",
     verdict="blocked", blocker="The product most people mean by 'NotebookLM' has no public API at all.", evidence="https://cloud.google.com/gemini", source="trained_knowledge"),
dict(id=92, app="Otter.ai", category="AI/Research/Media", one_liner="AI meeting transcription/notes.",
     auth=["Bearer API key"], self_serve="gated", gate_reason="CONFIRMED via live check: the MCP connector itself is free-plan-friendly, but the underlying Public REST API and webhooks (Bearer token, created under Integrations > Developer) are Enterprise-only, provisioned via account manager.",
     api_surface="REST (conversations, transcripts, action items, insights) + webhooks — Enterprise-only", mcp="Official Otter MCP server (available on lower tiers, but thinly documented)",
     verdict="partial", blocker="Full programmatic (non-MCP) access requires an Enterprise plan and manual enablement.", evidence="https://help.otter.ai/hc/en-us/articles/36130822688279-Otter-ai-Public-API", source="live_search"),
dict(id=93, app="Fathom", category="AI/Research/Media", one_liner="AI meeting recorder/notetaker.",
     auth=["API key"], self_serve="self-serve", gate_reason="API access self-serve on paid Team plans; key from settings.",
     api_surface="REST (narrow: meetings, transcripts, webhooks)", mcp="None official",
     verdict="ready", blocker="No free tier for API access.", evidence="https://fathom.video/", source="trained_knowledge"),
dict(id=94, app="Consensus", category="AI/Research/Media", one_liner="AI-powered academic-research search engine.",
     auth=["OAuth2 (requested/in development)"], self_serve="gated", gate_reason="No public developer API found; OAuth is referenced as forthcoming, not currently self-serve.",
     api_surface="No public API surface found", mcp="None found",
     verdict="blocked", blocker="No public API at all as of this research pass.", evidence="https://consensus.app/", source="trained_knowledge"),
dict(id=95, app="Reducto", category="AI/Research/Media", one_liner="Document parsing / extraction API for AI pipelines.",
     auth=["API key"], self_serve="self-serve", gate_reason="Free trial credits, key from dashboard.",
     api_surface="REST (narrow-medium: parse, extract, split)", mcp="None official",
     verdict="ready", blocker=None, evidence="https://reducto.ai/", source="trained_knowledge"),
dict(id=96, app="Devin", category="AI/Research/Media", one_liner="Cognition's autonomous AI software engineer.",
     auth=["API key (Bearer)"], self_serve="gated", gate_reason="Requires a paid Devin account; API key generated from Settings once subscribed.",
     api_surface="REST (v3, broad: sessions, playbooks, knowledge, scheduling)", mcp="Official Devin MCP at mcp.devin.ai — already listed as a Composio toolkit",
     verdict="ready", blocker="No free tier — needs a paid Devin seat before key issuance.", evidence="https://docs.devin.ai/work-with-devin/devin-mcp", source="live_search"),
dict(id=97, app="higgsfield", category="AI/Research/Media", one_liner="AI content/video generation suite with a CLI.",
     auth=["API key"], self_serve="self-serve", gate_reason="Self-serve signup with credits; key from dashboard.",
     api_surface="REST (narrow: generation jobs) + CLI wrapper", mcp="None found",
     verdict="ready", blocker=None, evidence="https://higgsfield.ai/", source="trained_knowledge"),
dict(id=98, app="Mermaid CLI", category="AI/Research/Media", one_liner="Command-line renderer for Mermaid diagrams.",
     auth=["N/A"], self_serve="self-serve", gate_reason="Open-source npm CLI tool — no account, no auth, no hosted API.",
     api_surface="No API — local CLI/Node library", mcp="None (not applicable — it's a local rendering tool, easily wrapped as a code/CLI tool)",
     verdict="ready", blocker="Not a SaaS API — 'buildable' here means wrapping a local binary, not integrating a hosted service.", evidence="https://github.com/mermaid-js/mermaid-cli", source="trained_knowledge"),
dict(id=99, app="YouTube Transcript (transcriptapi.com)", category="AI/Research/Media", one_liner="Third-party API for fetching YouTube video transcripts.",
     auth=["API key"], self_serve="self-serve", gate_reason="Self-serve signup with a free quota, key from dashboard.",
     api_surface="REST (narrow: single transcript-fetch endpoint)", mcp="None found",
     verdict="ready", blocker="Legal/ToS gray area since it's an unofficial layer over YouTube data, not a YouTube-sanctioned API.", evidence="https://transcriptapi.com/", source="trained_knowledge"),
dict(id=100, app="Grain", category="AI/Research/Media", one_liner="AI meeting recording & highlights tool.",
     auth=["API key"], self_serve="gated", gate_reason="API access is a Business-plan feature; not on free/Starter tiers.",
     api_surface="REST (narrow-medium: recordings, highlights, webhooks)", mcp="None found",
     verdict="ready", blocker="Requires a paid Business plan for API access.", evidence="https://grain.com/", source="trained_knowledge"),
]

if __name__ == "__main__":
    print(f"Loaded {len(APPS)} apps")
